import org.gradle.api.tasks.WriteProperties
import xyz.jpenilla.resourcefactory.bukkit.Permission

plugins {
    `java-library`
    id("com.gradleup.shadow") version "9.6.1"
    // https://kotlinlang.org/docs/releases.html
    kotlin("jvm")
    // https://github.com/Kotlin/kotlinx.serialization
    kotlin("plugin.serialization")
    // https://plugins.gradle.org/plugin/io.papermc.paperweight.userdev
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
    // https://github.com/jpenilla/run-task
    id("xyz.jpenilla.run-paper") version "3.1.0"
    // https://github.com/jpenilla/resource-factory
    id("xyz.jpenilla.resource-factory-paper-convention") version "1.3.1"
}

group = "eternalscript"
val runtimeVersion = providers.gradleProperty("runtimeVersion").get()
val javaVersion = providers.gradleProperty("javaVersion").map(String::toInt).get()
val pluginApiVersion = "26.2"
val minecraftVersion = "26.2"
val paperBuild = "112-stable"
val paperVersion = "$minecraftVersion.build.$paperBuild"
val managementPermissionActions = listOf(
    "help",
    "reload",
    "load",
    "unload",
    "clear",
    "config",
    "list",
    "status"
)
project.version = runtimeVersion
val minecraftHeapSize = 8
val minecraftArgs = listOf(
    "-Xmx${minecraftHeapSize}G",
    "-Xms${minecraftHeapSize}G",
    "-XX:+AlwaysPreTouch",
    "-XX:+DisableExplicitGC",
    "-XX:+ParallelRefProcEnabled",
    "-XX:+PerfDisableSharedMem",
    "-XX:+UnlockExperimentalVMOptions",
    "-XX:+UseG1GC",
    "-XX:G1HeapRegionSize=8M",
    "-XX:G1HeapWastePercent=5",
    "-XX:G1MaxNewSizePercent=40",
    "-XX:G1MixedGCCountTarget=4",
    "-XX:G1MixedGCLiveThresholdPercent=90",
    "-XX:G1NewSizePercent=30",
    "-XX:G1RSetUpdatingPauseTimePercent=5",
    "-XX:G1ReservePercent=20",
    "-XX:InitiatingHeapOccupancyPercent=15",
    "-XX:MaxGCPauseMillis=200",
    "-XX:MaxTenuringThreshold=1",
    "-XX:SurvivorRatio=32",
    "-Dusing.aikars.flags=https://mcflags.emc.gs",
    "-Daikars.new.flags=true"
)
val kotlinVersion = providers.gradleProperty("kotlinVersion").get()
val runtimeLibraries = listOf(
    "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion",
    "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion",
    "org.jetbrains.kotlin:kotlin-compiler-embeddable:$kotlinVersion",
    "org.jetbrains.kotlin:kotlin-script-runtime:$kotlinVersion",
    "org.jetbrains.kotlin:kotlin-scripting-common:$kotlinVersion",
    "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:$kotlinVersion",
    "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0",
    "org.jetbrains.kotlin:kotlin-scripting-jvm:$kotlinVersion",
    "org.jetbrains.kotlin:kotlin-scripting-jvm-host:$kotlinVersion",
    "org.jetbrains.kotlin:kotlin-metadata-jvm:$kotlinVersion",
    "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.11.0",
    "org.xerial:sqlite-jdbc:3.53.4.0"
)
val projectJavaLauncher = javaToolchains.launcherFor {
    languageVersion.set(JavaLanguageVersion.of(javaVersion))
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":ide-protocol"))
    paperweight.paperDevBundle(paperVersion)
    runtimeLibraries.forEach { coordinate ->
        compileOnly(coordinate)
        testImplementation(coordinate)
    }
    implementation("org.bstats:bstats-bukkit:3.2.1")
    testImplementation(kotlin("test", kotlinVersion))
}

val generateRuntimeLibraries = tasks.register<WriteProperties>("generateRuntimeLibraries") {
    destinationFile.set(
        layout.buildDirectory.file(
            "generated/eternalscript/eternalscript-runtime-libraries.properties"
        )
    )
    encoding = "UTF-8"
    lineSeparator = "\n"
    comment = "Generated by the EternalScript build; do not edit."
    property("libraries", runtimeLibraries.joinToString(","))
}

tasks {
    runServer {
        minecraftVersion(minecraftVersion)
        javaLauncher.set(projectJavaLauncher)
        jvmArgs(minecraftArgs)
    }
    processResources {
        from(generateRuntimeLibraries)
    }
    compileJava {
        options.release = javaVersion
    }
    jar {
        archiveClassifier.set("plain")
    }
    shadowJar {
        archiveClassifier.set("")
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
        relocate("org.bstats", "eternalscript.libs.bstats")
    }
}

tasks.register("releaseCheck") {
    group = "verification"
    description = "Builds and verifies the runtime and IntelliJ release artifacts."
    dependsOn(
        ":build",
        ":ide-protocol:build",
        ":intellij-plugin:build",
        ":intellij-plugin:verifyPlugin"
    )
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(javaVersion)
}

kotlin {
    explicitApi()
    jvmToolchain(javaVersion)
}

paperPluginYaml {
    name = rootProject.name
    main = pluginMain()
    version = runtimeVersion
    apiVersion = pluginApiVersion
    loader = "${pluginMain()}Loader"
    permissions.register("eternalscript.admin") {
        description = "Allows every EternalScript management command"
        default = Permission.Default.OP
        children(*managementPermissionActions.map { action ->
            "eternalscript.command.$action"
        }.toTypedArray())
    }
    managementPermissionActions.forEach { action ->
        permissions.register("eternalscript.command.$action") {
            description = "Allows /es $action"
            default = Permission.Default.FALSE
        }
    }
}

fun pluginMain() = "$group.${rootProject.name}"
