package eternalScript.core.script.project

import kotlin.script.experimental.api.ResultWithDiagnostics
import kotlin.script.experimental.api.ScriptDiagnostic

data class ScriptProjectDiagnostic(
    val report: ScriptDiagnostic,
    val sourceName: String,
    val line: Int?,
    val column: Int?
)

/** Maps generated-module failures back to ordinary Kotlin source files. */
fun ScriptProjectSource.failureDiagnostics(
    result: ResultWithDiagnostics<*>
): List<ScriptProjectDiagnostic> =
    result.reports
        .asSequence()
        .filter { report ->
            report.severity == ScriptDiagnostic.Severity.ERROR ||
                report.severity == ScriptDiagnostic.Severity.FATAL
        }
        .map { report ->
            val location = report.location?.start
            val reportSource = report.sourcePath
            val position = reportSource?.let { source ->
                location?.let { current ->
                    position(source, current.line, current.col)
                }
            }
            val fallbackSource = when {
                reportSource == null -> PROJECT_SCRIPT_NAME
                module.ownsSource(reportSource) -> PROJECT_SCRIPT_NAME
                else -> reportSource
            }
            ScriptProjectDiagnostic(
                report = report,
                sourceName = position?.sourceName ?: fallbackSource,
                line = position?.line ?: location?.line,
                column = position?.column ?: location?.col
            )
        }
        .distinctBy { diagnostic ->
            "${diagnostic.sourceName}:${diagnostic.line}:${diagnostic.column}:${diagnostic.report.message}"
        }
        .toList()

/** Maps a runtime exception frame from generated bytecode back to its Kotlin source. */
fun ScriptProjectSource.runtimePosition(
    exception: Throwable
): ScriptProjectPosition? =
    exception.relatedThrowables()
        .flatMap { current ->
            current.stackTrace.asSequence()
        }
        .firstNotNullOfOrNull { frame ->
            projectPositionOrNull(frame)
        }

/** Rewrites generated frames so server-side callback logs name the user source file. */
fun ScriptProjectSource.remapRuntimeStackTrace(
    exception: Throwable
): Throwable {
    exception.relatedThrowables().forEach { current ->
        current.stackTrace = current.stackTrace.map { frame ->
            val position = projectPositionOrNull(frame) ?: return@map frame
            StackTraceElement(
                frame.className,
                frame.methodName,
                position.sourceName,
                position.line
            )
        }.toTypedArray()
    }
    return exception
}

private fun ScriptProjectSource.projectPositionOrNull(
    frame: StackTraceElement
) =
    frame.fileName
        ?.takeIf { frame.lineNumber > 0 }
        ?.let { sourceName ->
            position(frame.className, sourceName, frame.lineNumber, 1)
        }

private fun Throwable.relatedThrowables(): Sequence<Throwable> = sequence {
    val pending = ArrayDeque<Throwable>()
    val visited = mutableSetOf<Throwable>()
    pending.add(this@relatedThrowables)

    while (pending.isNotEmpty()) {
        val current = pending.removeFirst()
        if (!visited.add(current)) continue
        yield(current)
        current.cause?.let(pending::addLast)
        current.suppressed.forEach(pending::addLast)
    }
}
